
2023-05-26 17:37:45,937 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 56, in get
    self.write(56.88)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 918, in write
    raise TypeError(message)
TypeError: write() only accepts bytes, unicode, and dict objects
2023-05-26 17:37:45,939 - ERROR - 500 GET /weather (::1) 239.97ms
2023-05-30 22:16:22,218 - INFO - This is an informational message.
2023-05-30 22:16:22,218 - WARNING - This is a warning message.
2023-05-30 22:16:22,218 - ERROR - This is an error message.
2023-05-30 22:16:22,219 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 56, in get
    self.write(56.88)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 918, in write
    raise TypeError(message)
TypeError: write() only accepts bytes, unicode, and dict objects
2023-05-30 22:16:22,221 - ERROR - 500 GET /weather (::1) 208.67ms
2023-05-30 22:16:23,287 - INFO - This is an informational message.
2023-05-30 22:16:23,287 - WARNING - This is a warning message.
2023-05-30 22:16:23,288 - ERROR - This is an error message.
2023-05-30 22:16:23,288 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 56, in get
    self.write(56.88)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 918, in write
    raise TypeError(message)
TypeError: write() only accepts bytes, unicode, and dict objects
2023-05-30 22:16:23,290 - ERROR - 500 GET /weather (::1) 165.90ms
2023-05-30 22:22:33,103 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 56, in get
    self.write(56.88)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 918, in write
    raise TypeError(message)
TypeError: write() only accepts bytes, unicode, and dict objects
2023-05-30 22:22:33,105 - ERROR - 500 GET /weather (::1) 172.74ms
2023-05-30 22:23:43,614 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 56, in get
    self.write(56.88)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 918, in write
    raise TypeError(message)
TypeError: write() only accepts bytes, unicode, and dict objects
2023-05-30 22:23:43,615 - ERROR - 500 GET /weather (::1) 160.07ms
2023-05-30 22:24:39,656 - INFO - 200 GET /weather (::1) 162.39ms
2023-05-30 23:27:16,476 - INFO - 200 GET /weather (::1) 194.94ms
2023-06-01 15:34:34,325 - INFO - 304 GET / (::1) 4.99ms
2023-06-01 15:34:38,317 - WARNING - SSL Error on 14 ('192.241.167.16', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
2023-06-01 15:34:38,319 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 37, in get
    weather_response = await http_client.fetch(WeatherURL)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/tcpclient.py", line 292, in connect
    stream = await stream.start_tls(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/iostream.py", line 1367, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
2023-06-01 15:34:38,338 - ERROR - 500 GET /weather (::1) 132.18ms
2023-06-01 15:34:38,442 - WARNING - SSL Error on 14 ('192.241.167.16', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
2023-06-01 15:34:38,443 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 37, in get
    weather_response = await http_client.fetch(WeatherURL)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/tcpclient.py", line 292, in connect
    stream = await stream.start_tls(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/iostream.py", line 1367, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
2023-06-01 15:34:38,444 - ERROR - 500 GET /weather (::1) 79.81ms
2023-06-01 15:34:58,732 - WARNING - SSL Error on 14 ('192.241.167.16', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
2023-06-01 15:34:58,733 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 37, in get
    weather_response = await http_client.fetch(WeatherURL)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/tcpclient.py", line 292, in connect
    stream = await stream.start_tls(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/iostream.py", line 1367, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
2023-06-01 15:34:58,734 - ERROR - 500 GET /weather (::1) 96.39ms
2023-06-01 15:34:59,684 - WARNING - SSL Error on 14 ('192.241.167.16', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
2023-06-01 15:34:59,685 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 37, in get
    weather_response = await http_client.fetch(WeatherURL)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/tcpclient.py", line 292, in connect
    stream = await stream.start_tls(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/iostream.py", line 1367, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
2023-06-01 15:34:59,687 - ERROR - 500 GET /weather (::1) 82.82ms
2023-06-01 15:36:15,207 - INFO - 200 GET /weather (::1) 297.19ms
2023-06-01 15:37:16,815 - INFO - 200 GET /weather (::1) 167.94ms
2023-06-01 16:38:07,701 - INFO - 200 GET /weather (::1) 256.05ms
2023-06-01 16:39:28,574 - INFO - 200 GET /weather (::1) 322.66ms
2023-06-01 18:34:14,293 - INFO - 200 GET /weather (::1) 198.69ms
2023-06-01 18:34:14,299 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 82, in get
    cur.execute(query, values)
psycopg2.errors.UndefinedTable: relation "telvvivweather" does not exist
LINE 2:                 INSERT INTO telvvivweather (temp, humidity, ...
                                    ^

2023-06-01 18:34:44,141 - INFO - 200 GET /weather (::1) 168.58ms
2023-06-01 18:34:44,143 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 82, in get
    cur.execute(query, values)
psycopg2.errors.UndefinedTable: relation "telvvivweather" does not exist
LINE 2:                 INSERT INTO telvvivweather (temp, humidity, ...
                                    ^

2023-06-01 18:39:37,328 - INFO - 200 GET /weather (::1) 172.07ms
2023-06-01 18:39:37,348 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 82, in get
    cur.execute(query, values)
psycopg2.errors.NumericValueOutOfRange: numeric field overflow
DETAIL:  A field with precision 3, scale 2 must round to an absolute value less than 10^1.

2023-06-01 18:44:29,785 - INFO - 200 GET /weather (::1) 194.56ms
2023-06-01 18:44:29,786 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 75, in get
    async with connection.cursor() as cur:
TypeError: 'psycopg2.extensions.cursor' object does not support the asynchronous context manager protocol
2023-06-01 18:48:27,589 - INFO - 200 GET /weather (::1) 162.48ms
2023-06-01 18:48:27,589 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 75, in get
    async with connection.cursor() as cur:
TypeError: 'psycopg2.extensions.cursor' object does not support the asynchronous context manager protocol
2023-06-01 18:48:28,892 - INFO - 200 GET /weather (::1) 158.41ms
2023-06-01 18:48:28,893 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 75, in get
    async with connection.cursor() as cur:
TypeError: 'psycopg2.extensions.cursor' object does not support the asynchronous context manager protocol
2023-06-01 18:50:06,972 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 68, in get
    async with connection.cursor() as cur:
TypeError: 'psycopg2.extensions.cursor' object does not support the asynchronous context manager protocol
2023-06-01 18:50:06,975 - ERROR - 500 GET /weather (::1) 187.60ms
2023-06-01 18:50:08,220 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 68, in get
    async with connection.cursor() as cur:
TypeError: 'psycopg2.extensions.cursor' object does not support the asynchronous context manager protocol
2023-06-01 18:50:08,222 - ERROR - 500 GET /weather (::1) 175.84ms
2023-06-01 18:50:18,758 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 68, in get
    async with connection.cursor() as cur:
TypeError: 'psycopg2.extensions.cursor' object does not support the asynchronous context manager protocol
2023-06-01 18:50:18,759 - ERROR - 500 GET /weather (::1) 168.52ms
2023-06-01 18:51:07,392 - INFO - 200 GET /weather (::1) 168.51ms
2023-06-05 09:42:49,003 - WARNING - 404 GET /favicon.ico (::1) 1.63ms
2023-06-05 09:42:50,380 - INFO - 200 GET /weather (::1) 270.00ms
2023-06-05 09:52:05,558 - INFO - 200 GET /weather (::1) 233.98ms
2023-06-05 10:43:58,666 - INFO - 200 GET /weather (::1) 226.45ms
2023-06-05 10:44:10,189 - WARNING - 400 GET /country (::1): Missing argument input_value
2023-06-05 10:44:10,190 - WARNING - 400 GET /country (::1) 0.64ms
2023-06-05 10:44:20,305 - WARNING - 400 GET /country (::1): Missing argument input_value
2023-06-05 10:44:20,305 - WARNING - 400 GET /country (::1) 1.00ms
2023-06-05 10:47:21,020 - INFO - 200 GET /weather (::1) 179.84ms
2023-06-05 10:47:25,423 - ERROR - Uncaught exception GET /country (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 70, in get
    self.write(country_data)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 918, in write
    raise TypeError(message)
TypeError: write() only accepts bytes, unicode, and dict objects. Lists not accepted for security reasons; see http://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.write
2023-06-05 10:47:25,429 - ERROR - 500 GET /country (::1) 176.32ms
2023-06-05 10:48:45,491 - INFO - 200 GET /country (::1) 287.98ms
2023-06-05 10:49:07,302 - INFO - 200 GET /country (::1) 138.40ms
2023-06-05 10:56:23,260 - ERROR - Uncaught exception GET /country (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 70, in get
    if country_response.status_code == 200 and isinstance(country_data, list):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTPResponse' object has no attribute 'status_code'
2023-06-05 10:56:23,263 - ERROR - 500 GET /country (::1) 133.15ms
2023-06-05 10:57:24,820 - ERROR - Uncaught exception GET /country (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 76, in get
    languages = [lang.get("name") for lang in country.get("languages")]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 76, in <listcomp>
    languages = [lang.get("name") for lang in country.get("languages")]
                 ^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2023-06-05 10:57:24,824 - ERROR - 500 GET /country (::1) 132.58ms
2023-06-05 10:57:30,255 - INFO - 200 GET /weather (::1) 166.80ms
2023-06-05 10:57:34,530 - ERROR - Uncaught exception GET /country (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 76, in get
    languages = [lang.get("name") for lang in country.get("languages")]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 76, in <listcomp>
    languages = [lang.get("name") for lang in country.get("languages")]
                 ^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2023-06-05 10:57:34,532 - ERROR - 500 GET /country (::1) 133.96ms
2023-06-05 11:01:18,940 - ERROR - Uncaught exception GET /country (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 84, in get
    self.write(f"languages: {', '.join(languages)}<br>")
                             ^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, NoneType found
2023-06-05 11:01:18,943 - ERROR - 500 GET /country (::1) 144.94ms
2023-06-05 11:02:58,523 - INFO - 200 GET /country (::1) 141.31ms
2023-06-05 11:09:45,199 - INFO - 200 GET /country (::1) 150.19ms
2023-06-05 11:09:46,501 - INFO - 200 GET /country (::1) 130.01ms
2023-06-05 11:10:10,470 - INFO - 200 GET /country (::1) 136.61ms
2023-06-05 11:10:13,065 - INFO - 200 GET /country (::1) 161.44ms
2023-06-05 11:12:00,423 - ERROR - Uncaught exception GET /country (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 84, in get
    self.write(f"{name} information:<br>")
                  ^^^^
UnboundLocalError: cannot access local variable 'name' where it is not associated with a value
2023-06-05 11:12:00,426 - ERROR - 500 GET /country (::1) 130.88ms
2023-06-05 11:12:26,067 - INFO - 200 GET /country (::1) 137.32ms
2023-06-05 11:12:51,645 - ERROR - Uncaught exception GET /country (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 84, in get
    self.write(f"{name} information:<br>")
                  ^^^^
UnboundLocalError: cannot access local variable 'name' where it is not associated with a value
2023-06-05 11:12:51,648 - ERROR - 500 GET /country (::1) 128.18ms
2023-06-05 11:16:04,840 - INFO - 200 GET /country (::1) 135.11ms
2023-06-05 11:16:39,323 - INFO - 200 GET /country (::1) 127.89ms
2023-06-05 11:17:12,032 - INFO - 200 GET /country (::1) 139.41ms
2023-06-05 11:18:21,107 - ERROR - Uncaught exception GET /country (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 79, in get
    capital = country.get("capital").get("capital")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
2023-06-05 11:18:21,111 - ERROR - 500 GET /country (::1) 150.95ms
2023-06-05 11:18:43,564 - INFO - 200 GET /country (::1) 132.83ms
2023-06-05 11:20:37,503 - INFO - 200 GET /country (::1) 130.57ms
2023-06-05 11:21:18,628 - INFO - 200 GET /weather (::1) 208.29ms
2023-06-05 11:27:06,099 - INFO - 200 GET /country (::1) 166.57ms
2023-06-05 11:33:28,881 - INFO - 200 GET /country (::1) 170.56ms
2023-06-05 15:06:14,949 - INFO - 200 GET /country (::1) 408.12ms
2023-06-05 15:06:24,171 - INFO - 200 GET /weather (::1) 245.29ms
2023-06-05 15:12:53,665 - ERROR - Uncaught exception GET /joke (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/joke', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 67, in get
    joke_data = json.loads(joke_response.body)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-06-05 15:12:53,672 - ERROR - 500 GET /joke (::1) 412.07ms
2023-06-05 15:16:19,734 - INFO - 200 GET /joke (::1) 194.03ms
2023-06-05 15:16:37,895 - INFO - 200 GET /joke (::1) 213.71ms
2023-06-05 15:16:43,187 - INFO - 200 GET /joke (::1) 215.07ms
2023-06-05 17:41:17,169 - ERROR - Uncaught exception GET /joke (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/joke', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 57, in get
    joke_response = await http_client.fetch(JokeURL, params = params)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/httpclient.py", line 286, in fetch
    request = HTTPRequest(url=request, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPRequest.__init__() got an unexpected keyword argument 'params'
2023-06-05 17:41:17,172 - ERROR - 500 GET /joke (::1) 5.96ms
2023-06-05 17:44:15,214 - INFO - 200 GET /joke (::1) 278.99ms
2023-06-05 17:44:27,308 - INFO - 200 GET /joke (::1) 201.84ms
2023-06-05 17:46:49,849 - INFO - 200 GET /joke (::1) 218.24ms
2023-06-05 17:47:30,701 - INFO - 200 GET /joke (::1) 557.78ms
2023-06-05 17:48:42,386 - INFO - 200 GET /joke (::1) 542.49ms
2023-06-05 17:48:45,970 - INFO - 200 GET /joke (::1) 497.50ms
2023-06-05 17:48:55,082 - INFO - 200 GET /joke (::1) 518.00ms
2023-06-05 17:49:03,622 - INFO - 200 GET /joke (::1) 460.99ms
2023-06-05 17:49:09,466 - INFO - 200 GET /joke (::1) 204.93ms
2023-06-05 20:47:16,158 - INFO - 200 GET /joke (::1) 309.37ms
2023-06-05 20:49:02,079 - INFO - 200 GET /joke (::1) 222.08ms
2023-06-05 20:52:51,619 - INFO - 200 GET /joke (::1) 235.47ms
2023-06-05 20:53:01,897 - INFO - 200 GET /joke (::1) 493.68ms
2023-06-05 20:53:42,247 - INFO - 200 GET /joke (::1) 246.16ms
2023-06-05 20:53:50,236 - INFO - 200 GET /joke (::1) 215.26ms
2023-06-05 20:53:53,082 - INFO - 200 GET /joke (::1) 215.04ms
2023-06-05 20:53:57,471 - INFO - 200 GET /joke (::1) 203.68ms
2023-06-05 20:54:04,644 - INFO - 200 GET /joke (::1) 535.90ms
2023-06-05 20:54:08,856 - INFO - 200 GET /joke (::1) 354.24ms
2023-06-05 20:54:15,271 - INFO - 200 GET /joke (::1) 251.41ms
2023-06-05 20:54:17,396 - INFO - 200 GET /joke (::1) 198.05ms
2023-06-05 20:54:34,259 - INFO - 200 GET /joke (::1) 207.11ms
2023-06-05 20:54:36,778 - INFO - 200 GET /joke (::1) 204.36ms
2023-06-05 20:54:41,141 - INFO - 200 GET /joke (::1) 198.51ms
2023-06-05 20:54:45,048 - INFO - 200 GET /joke (::1) 209.85ms
2023-06-05 20:54:50,376 - INFO - 200 GET /joke (::1) 197.68ms
2023-06-05 20:54:52,569 - INFO - 200 GET /joke (::1) 442.19ms
2023-06-05 20:54:54,981 - INFO - 200 GET /joke (::1) 209.68ms
2023-06-05 20:54:58,212 - INFO - 200 GET /joke (::1) 201.55ms
2023-06-05 20:57:36,467 - INFO - 200 GET /joke (::1) 227.85ms
2023-06-05 20:57:39,388 - INFO - 200 GET /joke (::1) 541.25ms
2023-06-05 20:57:42,547 - INFO - 200 GET /joke (::1) 194.71ms
2023-06-05 20:57:45,435 - INFO - 200 GET /joke (::1) 214.45ms
2023-06-05 20:57:47,128 - INFO - 200 GET /joke (::1) 219.59ms
2023-06-05 20:57:50,652 - INFO - 200 GET /joke (::1) 491.56ms
2023-06-05 20:57:53,540 - INFO - 200 GET /joke (::1) 205.10ms
2023-06-05 20:57:54,927 - INFO - 200 GET /joke (::1) 233.13ms
2023-06-05 20:58:19,977 - INFO - 200 GET /joke (::1) 209.17ms
2023-06-05 20:58:31,480 - INFO - 200 GET /joke (::1) 195.01ms
2023-06-05 20:58:34,071 - INFO - 200 GET /joke (::1) 516.38ms
2023-06-05 20:58:37,144 - INFO - 200 GET /joke (::1) 448.55ms
2023-06-05 20:58:39,019 - INFO - 200 GET /joke (::1) 207.93ms
2023-06-05 20:58:41,954 - INFO - 200 GET /joke (::1) 470.59ms
2023-06-05 20:58:50,046 - INFO - 200 GET /joke (::1) 193.82ms
2023-06-05 20:58:52,105 - INFO - 200 GET /joke (::1) 198.71ms
2023-06-05 20:58:57,057 - INFO - 200 GET /joke (::1) 207.83ms
2023-06-05 20:58:59,930 - INFO - 200 GET /joke (::1) 417.95ms
2023-06-05 20:59:01,625 - INFO - 200 GET /joke (::1) 426.17ms
2023-06-05 20:59:03,062 - INFO - 200 GET /joke (::1) 203.87ms
2023-06-05 21:07:52,172 - INFO - 200 GET /joke (::1) 303.65ms
2023-06-06 10:20:43,749 - INFO - 304 GET / (::1) 4.75ms
2023-06-06 10:20:48,495 - WARNING - SSL Error on 14 ('192.241.245.161', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
2023-06-06 10:20:48,496 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 167, in get
    weather_response = await http_client.fetch(WeatherURL)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/tcpclient.py", line 292, in connect
    stream = await stream.start_tls(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/iostream.py", line 1367, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
2023-06-06 10:20:48,509 - ERROR - 500 GET /weather (::1) 116.10ms
2023-06-06 10:20:48,609 - WARNING - SSL Error on 15 ('192.241.245.161', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
2023-06-06 10:20:48,610 - ERROR - Uncaught exception GET /weather (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/weather', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 167, in get
    weather_response = await http_client.fetch(WeatherURL)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/tcpclient.py", line 292, in connect
    stream = await stream.start_tls(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/iostream.py", line 1367, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
2023-06-06 10:20:48,611 - ERROR - 500 GET /weather (::1) 83.80ms
2023-06-06 10:22:54,333 - INFO - 200 GET /weather (::1) 451.95ms
2023-06-06 10:23:01,372 - INFO - 200 GET /country (::1) 236.64ms
2023-06-06 10:23:06,303 - INFO - 200 GET /joke (::1) 270.59ms
2023-06-06 10:26:52,386 - INFO - 200 GET /weather (::1) 165.00ms
2023-06-06 10:26:58,468 - INFO - 200 GET /weather (::1) 164.01ms
2023-06-06 10:26:58,635 - INFO - 200 GET /weather (::1) 164.97ms
2023-06-06 10:28:17,406 - INFO - 200 GET /weather (::1) 178.71ms
2023-06-06 10:28:23,163 - INFO - 200 GET /weather (::1) 165.68ms
2023-06-06 10:28:23,329 - INFO - 200 GET /weather (::1) 163.77ms
2023-06-06 10:29:19,982 - INFO - 200 GET /weather (::1) 159.98ms
2023-06-06 10:48:43,532 - INFO - 200 GET /joke (::1) 296.10ms
2023-06-06 10:52:23,268 - INFO - 200 GET /weather (::1) 1752.24ms
2023-06-06 10:52:23,714 - INFO - 200 GET /weather (::1) 442.09ms
2023-06-06 10:59:41,990 - INFO - 200 GET /weather (::1) 353.73ms
2023-06-06 10:59:42,159 - INFO - 200 GET /weather (::1) 165.76ms
2023-06-06 11:05:24,815 - INFO - 200 GET /joke (::1) 507.58ms
2023-06-06 11:05:46,995 - INFO - 200 GET /weather (::1) 1213.90ms
2023-06-06 11:05:47,159 - INFO - 200 GET /weather (::1) 160.02ms
2023-06-06 11:07:12,718 - INFO - 200 GET /weather (::1) 210.61ms
2023-06-06 11:07:20,099 - INFO - 200 GET /weather (::1) 164.44ms
2023-06-06 11:07:20,271 - INFO - 200 GET /weather (::1) 169.40ms
2023-06-06 11:08:21,443 - INFO - 200 GET /weather (::1) 329.57ms
2023-06-06 11:08:29,046 - INFO - Malformed HTTP message from ::1: Malformed HTTP version in HTTP Request-Line: 'ºº\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93ÊÊ\x00\x00\x00\x12\x00\x00\x00+\x00\x07\x06'
2023-06-06 11:08:29,048 - INFO - Malformed HTTP message from ::1: no colon in header line
2023-06-06 11:08:37,821 - INFO - 200 GET /weather (::1) 172.07ms
2023-06-06 11:14:14,136 - INFO - 200 GET /joke (::1) 266.77ms
2023-06-06 11:14:24,671 - WARNING - 404 GET /joke (::1) 1.26ms
2023-06-06 11:14:27,911 - WARNING - 404 GET /weather (::1) 0.75ms
2023-06-06 11:14:28,022 - WARNING - 404 GET /weather (::1) 0.39ms
2023-06-06 11:17:27,566 - WARNING - 404 GET /weather (::1) 0.38ms
2023-06-06 11:17:31,555 - WARNING - 404 GET /weather (::1) 0.53ms
2023-06-06 11:18:48,410 - INFO - 200 GET /weather (::1) 686.44ms
2023-06-06 11:20:16,595 - INFO - 200 GET /weather (::1) 167.85ms
2023-06-06 11:20:16,767 - INFO - 200 GET /weather (::1) 167.58ms
2023-06-06 11:26:00,664 - INFO - 200 GET /weather (::1) 175.22ms
2023-06-06 11:26:05,525 - INFO - 200 GET /weather (::1) 188.84ms
2023-06-06 11:26:05,700 - INFO - 200 GET /weather (::1) 173.02ms
2023-06-06 11:26:15,005 - INFO - 200 GET /weather (::1) 179.99ms
2023-06-06 11:26:15,198 - INFO - 200 GET /weather (::1) 190.05ms
2023-06-06 13:17:59,403 - INFO - 200 GET /weather (::1) 240.23ms
2023-06-06 13:17:59,586 - INFO - 200 GET /weather (::1) 180.75ms
2023-06-06 13:19:32,642 - INFO - 200 GET /weather (::1) 192.15ms
2023-06-06 13:19:32,817 - INFO - 200 GET /weather (::1) 172.24ms
2023-06-06 13:20:10,356 - INFO - 200 GET /weather (::1) 164.38ms
2023-06-06 13:20:13,230 - INFO - 200 GET /weather (::1) 263.77ms
2023-06-06 13:20:13,434 - INFO - 200 GET /weather (::1) 198.61ms
2023-06-06 13:20:33,763 - INFO - 200 GET /weather (::1) 269.04ms
2023-06-06 13:20:33,952 - INFO - 200 GET /weather (::1) 186.74ms
2023-06-06 13:21:21,787 - INFO - 200 GET /weather (::1) 187.73ms
2023-06-06 13:21:22,023 - INFO - 200 GET /weather (::1) 234.33ms
2023-06-06 13:23:01,251 - INFO - 200 GET /weather (::1) 206.88ms
2023-06-06 13:23:56,405 - INFO - 200 GET /weather (::1) 189.83ms
2023-06-06 13:24:01,238 - INFO - 200 GET /weather (::1) 197.28ms
2023-06-06 13:24:07,008 - INFO - 200 GET /weather (::1) 201.78ms
2023-06-06 13:24:07,740 - INFO - 200 GET /weather (::1) 728.56ms
2023-06-06 13:25:37,390 - INFO - 200 GET /weather (::1) 174.96ms
2023-06-06 13:25:41,245 - INFO - 200 GET /weather (::1) 182.61ms
2023-06-06 13:25:41,431 - INFO - 200 GET /weather (::1) 181.66ms
2023-06-06 13:30:44,012 - INFO - 200 GET /weather (::1) 233.10ms
2023-06-06 13:30:44,214 - INFO - 304 GET /weather (::1) 199.98ms
2023-06-06 13:38:27,505 - INFO - 200 GET /weather (::1) 238.99ms
2023-06-06 13:38:27,679 - INFO - 200 GET /weather (::1) 171.12ms
2023-06-06 13:39:02,209 - INFO - 200 GET /weather (::1) 189.98ms
2023-06-06 13:39:02,376 - INFO - 200 GET /weather (::1) 162.51ms
2023-06-06 13:43:26,136 - INFO - 200 GET /weather (::1) 187.21ms
2023-06-06 13:43:27,761 - INFO - 200 GET /weather (::1) 1185.29ms
2023-06-06 13:43:27,953 - INFO - 200 GET /weather (::1) 186.49ms
2023-06-06 13:43:44,337 - INFO - 200 GET /weather (::1) 191.08ms
2023-06-06 13:44:32,059 - INFO - 200 GET /weather (::1) 181.90ms
2023-06-06 13:45:03,543 - INFO - 200 GET /weather (::1) 183.96ms
2023-06-06 13:53:12,633 - INFO - 200 GET /weather (::1) 219.15ms
2023-06-06 13:59:40,386 - INFO - 200 GET /weather (::1) 178.54ms
2023-06-06 13:59:40,539 - INFO - 200 GET /weather (::1) 150.93ms
2023-06-06 13:59:44,205 - INFO - 200 GET /weather (::1) 174.00ms
2023-06-06 13:59:44,366 - INFO - 200 GET /weather (::1) 159.31ms
2023-06-06 14:00:31,578 - INFO - 200 GET /weather (::1) 156.83ms
2023-06-06 14:07:12,763 - INFO - 200 GET /weather (::1) 209.81ms
2023-06-06 14:07:48,535 - INFO - 200 GET /weather (::1) 174.56ms
2023-06-06 14:07:48,736 - INFO - 200 GET /weather (::1) 197.97ms
2023-06-06 14:07:49,340 - INFO - 200 GET /weather (::1) 192.24ms
2023-06-06 14:07:49,507 - INFO - 200 GET /weather (::1) 164.97ms
2023-06-06 14:07:49,684 - INFO - 200 GET /weather (::1) 173.12ms
2023-06-06 14:07:49,847 - INFO - 200 GET /weather (::1) 160.18ms
2023-06-06 14:07:50,025 - INFO - 200 GET /weather (::1) 173.95ms
2023-06-06 14:07:50,200 - INFO - 200 GET /weather (::1) 170.52ms
2023-06-06 14:07:50,369 - INFO - 200 GET /weather (::1) 165.79ms
2023-06-06 14:07:50,534 - INFO - 200 GET /weather (::1) 160.84ms
2023-06-06 14:07:50,716 - INFO - 200 GET /weather (::1) 178.98ms
2023-06-06 14:07:50,893 - INFO - 200 GET /weather (::1) 173.31ms
2023-06-06 14:07:51,076 - INFO - 200 GET /weather (::1) 179.36ms
2023-06-06 14:07:51,257 - INFO - 200 GET /weather (::1) 177.07ms
2023-06-06 14:07:51,431 - INFO - 200 GET /weather (::1) 170.36ms
2023-06-06 14:07:51,613 - INFO - 200 GET /weather (::1) 177.94ms
2023-06-06 14:07:51,797 - INFO - 200 GET /weather (::1) 180.30ms
2023-06-06 14:07:51,968 - INFO - 200 GET /weather (::1) 167.43ms
2023-06-06 14:07:52,387 - INFO - 200 GET /weather (::1) 415.86ms
2023-06-06 14:07:52,560 - INFO - 200 GET /weather (::1) 169.69ms
2023-06-06 14:07:52,795 - INFO - 200 GET /weather (::1) 231.37ms
2023-06-06 14:07:53,000 - INFO - 200 GET /weather (::1) 199.98ms
2023-06-06 14:07:53,207 - INFO - 200 GET /weather (::1) 202.06ms
2023-06-06 14:07:53,374 - INFO - 200 GET /weather (::1) 164.99ms
2023-06-06 14:07:53,542 - INFO - 304 GET /weather (::1) 164.34ms
2023-06-06 14:07:53,713 - INFO - 200 GET /weather (::1) 166.84ms
2023-06-06 14:07:53,888 - INFO - 200 GET /weather (::1) 171.40ms
2023-06-06 14:07:54,083 - INFO - 200 GET /weather (::1) 191.98ms
2023-06-06 14:07:54,251 - INFO - 200 GET /weather (::1) 164.62ms
2023-06-06 14:07:54,412 - INFO - 200 GET /weather (::1) 156.01ms
2023-06-06 14:07:54,579 - INFO - 200 GET /weather (::1) 164.94ms
2023-06-06 14:07:54,753 - INFO - 200 GET /weather (::1) 169.67ms
2023-06-06 14:07:54,933 - INFO - 200 GET /weather (::1) 174.09ms
2023-06-06 14:07:55,104 - INFO - 200 GET /weather (::1) 166.78ms
2023-06-06 14:07:55,263 - INFO - 200 GET /weather (::1) 154.85ms
2023-06-06 14:07:55,434 - INFO - 200 GET /weather (::1) 167.85ms
2023-06-06 14:07:55,607 - INFO - 200 GET /weather (::1) 167.35ms
2023-06-06 14:07:55,813 - INFO - 200 GET /weather (::1) 203.19ms
2023-06-06 14:07:55,984 - INFO - 200 GET /weather (::1) 167.51ms
2023-06-06 14:07:56,149 - INFO - 200 GET /weather (::1) 162.24ms
2023-06-06 14:07:56,318 - INFO - 200 GET /weather (::1) 166.21ms
2023-06-06 14:07:56,476 - INFO - 200 GET /weather (::1) 154.83ms
2023-06-06 14:07:56,654 - INFO - 200 GET /weather (::1) 174.42ms
2023-06-06 14:07:56,856 - INFO - 200 GET /weather (::1) 173.69ms
2023-06-06 14:07:57,021 - INFO - 200 GET /weather (::1) 159.85ms
2023-06-06 14:07:57,193 - INFO - 200 GET /weather (::1) 168.44ms
2023-06-06 14:07:57,376 - INFO - 200 GET /weather (::1) 162.42ms
2023-06-06 14:07:57,538 - INFO - 200 GET /weather (::1) 159.77ms
2023-06-06 14:07:57,703 - INFO - 200 GET /weather (::1) 161.93ms
2023-06-06 14:07:57,877 - INFO - 200 GET /weather (::1) 165.97ms
2023-06-06 14:07:58,099 - INFO - 200 GET /weather (::1) 219.02ms
2023-06-06 14:07:58,281 - INFO - 200 GET /weather (::1) 170.43ms
2023-06-06 14:07:58,451 - INFO - 200 GET /weather (::1) 167.16ms
2023-06-06 14:07:58,605 - INFO - 200 GET /weather (::1) 151.68ms
2023-06-06 14:07:58,767 - INFO - 200 GET /weather (::1) 160.37ms
2023-06-06 14:08:01,137 - INFO - 200 GET /weather (::1) 188.33ms
2023-06-06 14:08:01,316 - INFO - 200 GET /weather (::1) 174.51ms
2023-06-06 14:08:58,681 - INFO - 200 GET /weather (::1) 176.03ms
2023-06-06 14:09:09,669 - INFO - 200 GET /weather (::1) 180.59ms
2023-06-06 14:22:27,694 - INFO - 200 GET /weather (::1) 263.95ms
2023-06-06 14:22:36,462 - INFO - 200 GET /weather (::1) 175.22ms
2023-06-06 14:26:19,470 - INFO - 200 GET /weather (::1) 170.29ms
2023-06-06 14:26:19,720 - INFO - 200 GET /weather (::1) 247.94ms
2023-06-06 14:26:52,015 - INFO - 200 GET /weather (::1) 163.98ms
2023-06-06 14:30:17,375 - INFO - 200 GET /weather (::1) 165.57ms
2023-06-06 14:30:17,583 - INFO - 200 GET /weather (::1) 205.56ms
2023-06-06 14:30:20,511 - INFO - 200 GET /weather (::1) 185.19ms
2023-06-06 14:30:20,682 - INFO - 200 GET /weather (::1) 168.57ms
2023-06-06 14:30:22,133 - INFO - 200 GET /weather (::1) 171.45ms
2023-06-06 14:30:22,304 - INFO - 200 GET /weather (::1) 167.94ms
2023-06-06 14:30:24,656 - INFO - 200 GET /weather (::1) 172.48ms
2023-06-06 14:30:24,826 - INFO - 200 GET /weather (::1) 166.27ms
2023-06-06 14:30:48,632 - INFO - 200 GET /weather (::1) 184.84ms
2023-06-06 14:30:50,940 - INFO - 200 GET /weather (::1) 171.45ms
2023-06-06 14:30:51,107 - INFO - 200 GET /weather (::1) 164.90ms
2023-06-06 14:32:27,515 - INFO - 200 GET /weather (::1) 158.63ms
2023-06-06 14:32:30,519 - INFO - 200 GET /weather (::1) 204.38ms
2023-06-06 14:32:30,688 - INFO - 200 GET /weather (::1) 166.67ms
2023-06-06 14:32:32,122 - INFO - 200 GET /weather (::1) 166.04ms
2023-06-06 14:32:32,292 - INFO - 304 GET /weather (::1) 167.49ms
2023-06-06 14:32:58,367 - INFO - 200 GET /weather (::1) 174.20ms
2023-06-07 13:26:17,039 - INFO - 200 GET /weather (::1) 289.94ms
2023-06-07 13:49:51,184 - INFO - 200 GET /weather (::1) 214.18ms
2023-06-07 13:51:35,244 - INFO - 200 GET /weather (::1) 193.78ms
2023-06-07 13:51:35,408 - INFO - 200 GET /weather (::1) 160.10ms
2023-06-07 13:51:38,576 - INFO - 200 GET /weather (::1) 173.48ms
2023-06-07 13:51:38,738 - INFO - 200 GET /weather (::1) 158.56ms
2023-06-07 13:52:13,222 - INFO - 200 GET /weather (::1) 195.81ms
2023-06-07 13:52:20,260 - INFO - 200 GET /weather (::1) 308.83ms
2023-06-07 13:52:20,453 - INFO - 200 GET /weather (::1) 190.95ms
2023-06-07 13:52:54,716 - INFO - 200 GET /weather (::1) 158.24ms
2023-06-07 13:53:36,917 - INFO - 200 GET /weather (::1) 164.70ms
2023-06-07 13:53:37,075 - INFO - 200 GET /weather (::1) 153.52ms
2023-06-07 13:56:59,095 - INFO - 200 GET /weather (::1) 169.99ms
2023-06-07 13:56:59,252 - INFO - 200 GET /weather (::1) 153.71ms
2023-06-07 13:57:03,432 - INFO - 200 GET /weather (::1) 160.14ms
2023-06-07 13:57:03,590 - INFO - 200 GET /weather (::1) 155.67ms
2023-06-07 13:57:06,094 - INFO - 200 GET /weather (::1) 177.53ms
2023-06-07 13:57:06,406 - INFO - 200 GET /weather (::1) 309.82ms
2023-06-07 13:59:20,216 - INFO - 200 GET /weather (::1) 166.59ms
2023-06-07 13:59:26,751 - INFO - 200 GET /weather (::1) 152.45ms
2023-06-07 13:59:26,967 - INFO - 200 GET /weather (::1) 213.68ms
2023-06-07 13:59:43,905 - INFO - 200 GET /weather (::1) 196.56ms
2023-06-07 14:00:43,012 - INFO - 200 GET /weather (::1) 205.15ms
2023-06-07 14:00:48,426 - INFO - 200 GET /weather (::1) 175.71ms
2023-06-07 14:00:48,586 - INFO - 200 GET /weather (::1) 157.09ms
2023-06-07 14:05:57,639 - INFO - 200 GET /country (::1) 288.11ms
2023-06-07 14:06:21,308 - ERROR - Uncaught exception GET /country (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 129, in get
    country_data['response_time'] = formatted_response_time
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
2023-06-07 14:06:21,314 - ERROR - 500 GET /country (::1) 136.52ms
2023-06-07 14:11:01,495 - ERROR - Uncaught exception GET /country (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 166, in get
    self.write(updated_country_data)
               ^^^^^^^^^^^^^^^^^^^^
NameError: name 'updated_country_data' is not defined
2023-06-07 14:11:01,521 - ERROR - 500 GET /country (::1) 170.59ms
2023-06-07 14:11:39,528 - ERROR - Uncaught exception GET /country (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 166, in get
    self.write(country_data)
               ^^^^^^^^^^^^^^
NameError: name 'updated_country_data' is not defined
2023-06-07 14:11:39,530 - ERROR - 500 GET /country (::1) 132.23ms
2023-06-07 14:11:50,601 - ERROR - Uncaught exception GET /country (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 166, in get
    self.write(country_data)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 918, in write
    raise TypeError(message)
TypeError: write() only accepts bytes, unicode, and dict objects. Lists not accepted for security reasons; see http://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.write
2023-06-07 14:11:50,604 - ERROR - 500 GET /country (::1) 138.16ms
2023-06-07 14:14:17,806 - INFO - 200 GET /country (::1) 144.09ms
2023-06-07 14:20:01,991 - INFO - 200 GET /country (::1) 132.89ms
2023-06-07 14:20:02,139 - INFO - 200 GET /country (::1) 132.51ms
2023-06-07 14:20:02,171 - INFO - 200 GET /weather (::1) 313.94ms
2023-06-07 14:20:02,424 - INFO - 200 GET /weather (::1) 248.49ms
2023-06-07 14:20:10,664 - INFO - 200 GET /country (::1) 134.70ms
2023-06-07 14:20:10,789 - INFO - 200 GET /country (::1) 122.47ms
2023-06-07 14:20:10,796 - INFO - 200 GET /weather (::1) 266.98ms
2023-06-07 14:20:10,970 - INFO - 200 GET /weather (::1) 170.97ms
2023-06-07 14:20:44,934 - INFO - 200 GET /country (::1) 396.31ms
2023-06-07 14:20:45,004 - INFO - 200 GET /weather (::1) 466.38ms
2023-06-07 14:25:53,550 - INFO - 200 GET /country (::1) 132.72ms
2023-06-07 14:25:53,565 - INFO - 200 GET /weather (::1) 148.26ms
2023-06-07 14:25:53,682 - INFO - 200 GET /country (::1) 129.20ms
2023-06-07 14:25:53,726 - INFO - 200 GET /weather (::1) 158.22ms
2023-06-07 14:27:48,831 - INFO - 200 GET /country (::1) 139.86ms
2023-06-07 14:27:48,876 - INFO - 200 GET /weather (::1) 185.21ms
2023-06-07 14:28:14,301 - INFO - 200 GET /country (::1) 140.00ms
2023-06-07 14:28:14,426 - INFO - 200 GET /country (::1) 122.54ms
2023-06-07 14:28:14,479 - INFO - 200 GET /weather (::1) 318.45ms
2023-06-07 14:28:14,664 - INFO - 200 GET /weather (::1) 182.05ms
2023-06-07 14:28:20,561 - INFO - 200 GET /country (::1) 132.69ms
2023-06-07 14:28:20,596 - INFO - 200 GET /weather (::1) 167.94ms
2023-06-07 14:28:20,695 - INFO - 200 GET /country (::1) 128.74ms
2023-06-07 14:28:20,771 - INFO - 200 GET /weather (::1) 172.93ms
2023-06-07 14:29:30,259 - INFO - 200 GET /weather (::1) 197.56ms
2023-06-07 14:29:30,611 - INFO - 200 GET /country (::1) 550.27ms
2023-06-07 14:30:35,989 - INFO - 200 GET /country (::1) 128.74ms
2023-06-07 14:30:36,175 - INFO - 200 GET /weather (::1) 315.10ms
2023-06-07 14:30:48,877 - INFO - 200 GET /country (::1) 135.59ms
2023-06-07 14:30:48,894 - INFO - 200 GET /weather (::1) 155.99ms
2023-06-07 14:30:49,000 - INFO - 200 GET /country (::1) 120.83ms
2023-06-07 14:30:49,064 - INFO - 200 GET /weather (::1) 166.72ms
2023-06-07 14:34:39,098 - INFO - 200 GET /weather (::1) 160.49ms
2023-06-07 14:34:39,278 - INFO - 200 GET /weather (::1) 175.66ms
2023-06-07 14:34:47,084 - INFO - 200 GET /weather (::1) 147.59ms
2023-06-07 14:34:47,266 - INFO - 200 GET /weather (::1) 179.68ms
2023-06-07 14:34:52,414 - WARNING - 405 GET /Israel (::1) 0.76ms
2023-06-07 14:35:18,929 - WARNING - 405 GET /America (::1) 0.79ms
2023-06-07 14:47:37,471 - INFO - 200 GET /weather (::1) 193.03ms
2023-06-07 14:47:41,944 - INFO - 200 GET /weather (::1) 626.69ms
2023-06-07 14:47:42,464 - INFO - 200 GET /weather (::1) 517.01ms
2023-06-07 14:47:48,539 - INFO - 200 GET /country (::1) 124.80ms
2023-06-07 14:48:00,551 - INFO - 200 GET /country (::1) 137.13ms
2023-06-07 14:53:31,375 - INFO - 200 GET /weather (::1) 193.44ms
2023-06-07 14:53:31,543 - INFO - 200 GET /weather (::1) 165.53ms
2023-06-07 14:53:36,044 - WARNING - 400 GET /country (::1): Missing argument name
2023-06-07 14:53:36,045 - WARNING - 400 GET /country (::1) 1.26ms
2023-06-07 14:53:46,774 - WARNING - 400 GET /country (::1): Missing argument name
2023-06-07 14:53:46,775 - WARNING - 400 GET /country (::1) 0.74ms
2023-06-07 18:28:26,433 - INFO - 200 GET /weather (::1) 567.40ms
2023-06-07 18:28:26,998 - INFO - 200 GET /weather (::1) 555.47ms
2023-06-07 18:28:29,710 - INFO - 200 GET /weather (::1) 515.64ms
2023-06-07 18:28:30,301 - INFO - 200 GET /weather (::1) 586.70ms
2023-06-07 18:28:38,474 - INFO - 200 GET /weather (::1) 155.61ms
2023-06-07 18:28:38,635 - INFO - 200 GET /weather (::1) 159.17ms
2023-06-07 18:28:48,369 - WARNING - 400 GET /country (::1): Missing argument name
2023-06-07 18:28:48,370 - WARNING - 400 GET /country (::1) 1.35ms
2023-06-07 18:29:06,692 - WARNING - 400 GET /country (::1): Missing argument name
2023-06-07 18:29:06,693 - WARNING - 400 GET /country (::1) 0.84ms
2023-06-07 18:29:13,963 - WARNING - 405 GET /country/Israel (::1) 0.41ms
2023-06-07 18:29:18,161 - WARNING - 400 GET /country (::1): Missing argument name
2023-06-07 18:29:18,161 - WARNING - 400 GET /country (::1) 0.93ms
2023-06-07 18:34:01,337 - INFO - 200 GET /weather (::1) 196.95ms
2023-06-07 18:34:01,526 - INFO - 200 GET /weather (::1) 186.16ms
2023-06-07 18:34:19,290 - WARNING - 400 GET /country (::1): Missing argument name
2023-06-07 18:34:19,290 - WARNING - 400 GET /country (::1) 0.59ms
2023-06-07 18:37:19,790 - INFO - 200 GET /weather (::1) 250.01ms
2023-06-07 18:37:19,995 - INFO - 200 GET /weather (::1) 200.60ms
2023-06-07 18:37:30,678 - WARNING - 400 GET /country (::1): Missing argument name
2023-06-07 18:37:30,678 - WARNING - 400 GET /country (::1) 1.22ms
2023-06-07 18:40:12,562 - INFO - 200 GET /weather (::1) 319.27ms
2023-06-07 18:40:12,736 - INFO - 200 GET /weather (::1) 169.94ms
2023-06-07 18:40:28,451 - WARNING - 400 GET /country (::1): Missing argument name
2023-06-07 18:40:28,452 - WARNING - 400 GET /country (::1) 1.21ms
2023-06-07 18:41:40,393 - INFO - 200 GET /weather (::1) 172.16ms
2023-06-07 18:41:47,962 - INFO - 200 GET /weather (::1) 164.55ms
2023-06-07 18:41:48,128 - INFO - 200 GET /weather (::1) 162.61ms
2023-06-07 18:41:53,951 - INFO - 200 GET /country?name=Israel (::1) 178.20ms
2023-06-07 18:42:02,872 - INFO - 200 GET /country?name=America (::1) 134.62ms
2023-06-07 18:42:16,382 - INFO - 200 GET /country?name=Poland (::1) 127.52ms
2023-06-07 18:44:47,259 - INFO - 200 GET /weather (::1) 150.65ms
2023-06-07 18:45:04,802 - INFO - 200 GET /country?name=america (::1) 146.87ms
2023-06-07 18:46:26,120 - INFO - 200 GET /weather (::1) 167.39ms
2023-06-07 18:47:00,351 - INFO - 200 GET /weather (::1) 164.42ms
2023-06-07 18:47:04,106 - INFO - 200 GET /weather (::1) 160.03ms
2023-06-07 18:47:24,274 - INFO - 200 GET /weather (::1) 163.43ms
2023-06-07 18:50:57,583 - INFO - 200 GET /weather (::1) 455.26ms
2023-06-07 18:51:17,274 - INFO - 200 GET /weather (::1) 163.20ms
2023-06-07 18:51:39,183 - INFO - 200 GET /country?name=Israel (::1) 135.70ms
2023-06-07 18:52:51,373 - INFO - 304 GET / (::1) 0.46ms
2023-06-07 18:52:57,220 - INFO - 200 GET /joke (::1) 603.46ms
2023-06-07 18:53:15,038 - INFO - 200 GET /joke (::1) 1543.50ms
2023-06-07 19:00:26,735 - INFO - 200 GET /weather (::1) 173.62ms
2023-06-07 19:00:26,904 - INFO - 200 GET /weather (::1) 165.46ms
2023-06-07 19:00:27,087 - INFO - 200 GET /joke (::1) 524.46ms
2023-06-07 19:00:27,529 - INFO - 200 GET /joke (::1) 439.67ms
2023-06-07 19:00:39,447 - INFO - 200 GET /weather (::1) 160.50ms
2023-06-07 19:00:39,744 - INFO - 200 GET /joke (::1) 458.08ms
2023-06-07 19:00:49,522 - INFO - 200 GET /weather (::1) 166.87ms
2023-06-07 19:00:49,692 - INFO - 304 GET /weather (::1) 167.55ms
2023-06-07 19:00:49,828 - INFO - 200 GET /joke (::1) 471.20ms
2023-06-07 19:00:50,037 - INFO - 200 GET /joke (::1) 204.85ms
2023-06-07 19:00:55,542 - INFO - 200 GET /weather (::1) 161.65ms
2023-06-07 19:00:55,716 - INFO - 200 GET /weather (::1) 166.19ms
2023-06-07 19:00:55,854 - INFO - 200 GET /joke (::1) 474.24ms
2023-06-07 19:00:56,056 - INFO - 200 GET /joke (::1) 199.05ms
2023-06-07 21:34:13,603 - INFO - 200 GET /joke (::1) 371.23ms
2023-06-07 21:34:13,608 - INFO - 200 GET /weather (::1) 373.85ms
2023-06-07 21:34:13,788 - INFO - 200 GET /weather (::1) 176.82ms
2023-06-07 21:34:14,085 - INFO - 200 GET /joke (::1) 476.80ms
2023-06-07 21:36:20,205 - INFO - 200 GET /weather (::1) 207.32ms
2023-06-07 21:36:20,383 - INFO - 200 GET /weather (::1) 174.97ms
2023-06-07 21:36:20,698 - INFO - 200 GET /joke (::1) 701.53ms
2023-06-07 21:36:20,915 - INFO - 200 GET /joke (::1) 214.02ms
2023-06-07 21:36:48,161 - ERROR - Uncaught exception GET /country?name=budapest (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country?name=budapest', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 118, in get
    country_response = await http_client.fetch(CountryURL)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.httpclient.HTTPClientError: HTTP 404: Not Found
2023-06-07 21:36:48,168 - ERROR - 500 GET /country?name=budapest (::1) 449.39ms
2023-06-07 21:36:50,650 - ERROR - Uncaught exception GET /country?name=budapest (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country?name=budapest', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 118, in get
    country_response = await http_client.fetch(CountryURL)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.httpclient.HTTPClientError: HTTP 404: Not Found
2023-06-07 21:36:50,652 - ERROR - 500 GET /country?name=budapest (::1) 157.62ms
2023-06-07 21:36:56,990 - INFO - 200 GET /country?name=Israel (::1) 133.24ms
2023-06-07 21:37:07,489 - INFO - 200 GET /country?name=Bolivia (::1) 134.43ms
2023-06-07 21:37:16,787 - INFO - 200 GET /country?name=Canada (::1) 162.42ms
2023-06-07 21:37:23,728 - INFO - 200 GET /country?name=India (::1) 189.41ms
2023-06-07 21:37:49,378 - INFO - 200 GET /weather (::1) 175.14ms
2023-06-07 21:37:49,558 - INFO - 200 GET /weather (::1) 176.30ms
2023-06-07 21:37:49,828 - INFO - 200 GET /joke (::1) 625.44ms
2023-06-07 21:37:50,024 - INFO - 200 GET /joke (::1) 191.90ms
2023-06-07 21:39:35,741 - INFO - 200 GET /weather (::1) 415.01ms
2023-06-07 21:39:35,777 - INFO - 200 GET /joke (::1) 452.74ms
2023-06-07 21:39:35,912 - INFO - 200 GET /weather (::1) 169.27ms
2023-06-07 21:39:36,250 - INFO - 200 GET /joke (::1) 469.23ms
2023-06-07 21:39:42,137 - INFO - 200 GET /country?name=Israel (::1) 362.10ms
2023-06-07 22:01:14,045 - INFO - 200 GET /weather (::1) 405.20ms
2023-06-07 22:01:14,228 - INFO - 200 GET /weather (::1) 179.06ms
2023-06-07 22:01:14,359 - INFO - 200 GET /joke (::1) 720.01ms
2023-06-07 22:01:14,569 - INFO - 200 GET /joke (::1) 199.99ms
2023-06-07 22:01:53,149 - INFO - 200 GET /weather (::1) 247.04ms
2023-06-07 22:01:53,152 - INFO - 200 GET /joke (::1) 250.33ms
2023-06-07 22:01:53,329 - INFO - 200 GET /weather (::1) 175.87ms
2023-06-07 22:01:53,802 - INFO - 200 GET /joke (::1) 647.87ms
2023-06-07 22:02:06,129 - INFO - 200 GET /weather (::1) 171.46ms
2023-06-07 22:02:06,386 - INFO - 200 GET /joke (::1) 429.42ms
2023-06-07 22:02:06,535 - INFO - 200 GET /weather (::1) 401.98ms
2023-06-07 22:02:06,611 - INFO - 200 GET /joke (::1) 222.50ms
2023-06-07 22:02:43,213 - INFO - 200 GET /weather (::1) 386.55ms
2023-06-07 22:02:43,242 - INFO - 200 GET /joke (::1) 416.82ms
2023-06-07 22:02:43,477 - INFO - 200 GET /weather (::1) 253.30ms
2023-06-07 22:02:43,479 - INFO - 200 GET /joke (::1) 234.13ms
2023-06-07 22:02:57,429 - ERROR - Uncaught exception GET /country?name=mauritius (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country?name=mauritius', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 135, in get
    'capital': capital,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'capital' where it is not associated with a value
2023-06-07 22:02:57,432 - ERROR - 500 GET /country?name=mauritius (::1) 158.50ms
2023-06-07 22:03:40,259 - INFO - 200 GET /weather (::1) 208.77ms
2023-06-07 22:03:40,302 - INFO - 200 GET /joke (::1) 252.20ms
2023-06-07 22:03:41,810 - INFO - 200 GET /joke (::1) 383.06ms
2023-06-07 22:03:41,845 - INFO - 200 GET /weather (::1) 417.82ms
2023-06-07 22:03:42,033 - INFO - 200 GET /weather (::1) 183.30ms
2023-06-07 22:03:42,041 - INFO - 200 GET /joke (::1) 227.85ms
2023-06-07 22:07:11,713 - INFO - 200 GET /weather (::1) 240.41ms
2023-06-07 22:07:11,907 - INFO - 200 GET /joke (::1) 434.57ms
2023-06-07 22:07:47,593 - INFO - 200 GET /weather (::1) 198.12ms
2023-06-07 22:07:47,694 - INFO - 200 GET /joke (::1) 298.99ms
2023-06-07 22:08:08,578 - INFO - 200 GET /weather (::1) 186.81ms
2023-06-07 22:08:08,901 - INFO - 200 GET /joke (::1) 510.35ms
2023-06-07 22:08:13,048 - INFO - 200 GET /weather (::1) 197.18ms
2023-06-07 22:08:13,221 - INFO - 200 GET /weather (::1) 170.67ms
2023-06-07 22:08:13,305 - INFO - 200 GET /joke (::1) 457.03ms
2023-06-07 22:08:13,540 - INFO - 200 GET /joke (::1) 233.12ms
2023-06-07 22:08:22,203 - INFO - 200 GET /weather (::1) 167.91ms
2023-06-07 22:08:22,469 - INFO - 200 GET /joke (::1) 434.67ms
2023-06-07 22:09:17,202 - ERROR - Uncaught exception GET /country?name=America (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country?name=America', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 135, in get
    'capital': capital,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'capital' where it is not associated with a value
2023-06-07 22:09:17,203 - ERROR - 500 GET /country?name=America (::1) 148.34ms
2023-06-07 22:09:19,295 - ERROR - Uncaught exception GET /country?name=America (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country?name=America', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 135, in get
    'capital': capital,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'capital' where it is not associated with a value
2023-06-07 22:09:19,296 - ERROR - 500 GET /country?name=America (::1) 146.73ms
2023-06-07 22:10:15,068 - INFO - 200 GET /weather (::1) 363.18ms
2023-06-07 22:10:15,236 - INFO - 200 GET /joke (::1) 532.21ms
2023-06-07 22:10:15,248 - INFO - 200 GET /weather (::1) 176.49ms
2023-06-07 22:10:15,451 - INFO - 200 GET /joke (::1) 212.91ms
2023-06-07 22:10:19,002 - ERROR - Uncaught exception GET /country?name=Israel (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country?name=Israel', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 135, in get
    'capital': capital,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'capital' where it is not associated with a value
2023-06-07 22:10:19,005 - ERROR - 500 GET /country?name=Israel (::1) 143.80ms
2023-06-07 22:11:30,846 - INFO - 200 GET /weather (::1) 177.48ms
2023-06-07 22:11:31,021 - INFO - 200 GET /weather (::1) 171.27ms
2023-06-07 22:11:31,146 - INFO - 200 GET /joke (::1) 480.14ms
2023-06-07 22:11:31,664 - INFO - 200 GET /joke (::1) 513.54ms
2023-06-07 22:12:07,841 - ERROR - Uncaught exception GET /country?name=America (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country?name=America', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 135, in get
    'capital': capital,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'capital' where it is not associated with a value
2023-06-07 22:12:07,842 - ERROR - 500 GET /country?name=America (::1) 141.25ms
2023-06-07 22:12:16,524 - INFO - 200 GET /weather (::1) 179.12ms
2023-06-07 22:12:16,708 - INFO - 200 GET /weather (::1) 180.90ms
2023-06-07 22:12:16,777 - INFO - 200 GET /joke (::1) 433.28ms
2023-06-07 22:12:17,233 - INFO - 200 GET /joke (::1) 451.92ms
2023-06-07 22:13:06,893 - INFO - 200 GET /weather (::1) 194.92ms
2023-06-07 22:13:07,205 - INFO - 200 GET /joke (::1) 507.60ms
2023-06-07 22:13:09,879 - ERROR - Uncaught exception GET /country?name=Israel (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country?name=Israel', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 135, in get
    'capital': capital,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'capital' where it is not associated with a value
2023-06-07 22:13:09,880 - ERROR - 500 GET /country?name=Israel (::1) 140.24ms
2023-06-07 22:13:22,959 - INFO - 200 GET /weather (::1) 231.39ms
2023-06-07 22:13:23,163 - INFO - 200 GET /joke (::1) 435.53ms
2023-06-07 22:14:18,387 - INFO - 200 GET /weather (::1) 180.54ms
2023-06-07 22:14:18,505 - INFO - 200 GET /joke (::1) 300.12ms
2023-06-07 22:14:18,613 - INFO - 200 GET /weather (::1) 221.46ms
2023-06-07 22:14:18,716 - INFO - 200 GET /joke (::1) 206.77ms
2023-06-07 22:14:22,173 - ERROR - Uncaught exception GET /country?name=America (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country?name=America', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 135, in get
    'capital': capital,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'capital' where it is not associated with a value
2023-06-07 22:14:22,176 - ERROR - 500 GET /country?name=America (::1) 156.59ms
2023-06-07 22:17:20,600 - INFO - 200 GET /weather (::1) 410.20ms
2023-06-07 22:17:20,606 - INFO - 200 GET /joke (::1) 422.86ms
2023-06-07 22:17:20,793 - INFO - 200 GET /weather (::1) 185.94ms
2023-06-07 22:17:21,024 - INFO - 200 GET /joke (::1) 412.61ms
2023-06-07 22:17:24,377 - ERROR - Uncaught exception GET /country?name=America (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country?name=America', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 136, in get
    'capital': capital,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'capital' where it is not associated with a value
2023-06-07 22:17:24,380 - ERROR - 500 GET /country?name=America (::1) 149.21ms
2023-06-07 22:18:10,833 - INFO - 200 GET /weather (::1) 404.15ms
2023-06-07 22:18:10,854 - INFO - 200 GET /joke (::1) 425.56ms
2023-06-07 22:18:31,166 - INFO - 200 GET /weather (::1) 199.45ms
2023-06-07 22:18:31,332 - INFO - 200 GET /weather (::1) 161.60ms
2023-06-07 22:18:31,409 - INFO - 200 GET /joke (::1) 444.32ms
2023-06-07 22:18:31,925 - INFO - 200 GET /joke (::1) 513.46ms
2023-06-07 22:18:36,197 - ERROR - Uncaught exception GET /country?name=america (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country?name=america', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 136, in get
    'capital': capital,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'capital' where it is not associated with a value
2023-06-07 22:18:36,199 - ERROR - 500 GET /country?name=america (::1) 142.72ms
2023-06-07 22:20:44,611 - INFO - 200 GET /weather (::1) 171.71ms
2023-06-07 22:20:44,703 - INFO - 200 GET /joke (::1) 263.46ms
2023-06-07 22:21:21,561 - INFO - 200 GET /weather (::1) 170.73ms
2023-06-07 22:21:21,586 - INFO - 200 GET /joke (::1) 199.02ms
2023-06-07 22:21:24,972 - INFO - 200 GET /weather (::1) 179.58ms
2023-06-07 22:21:25,159 - INFO - 200 GET /weather (::1) 184.33ms
2023-06-07 22:21:25,228 - INFO - 200 GET /joke (::1) 435.73ms
2023-06-07 22:21:25,704 - INFO - 200 GET /joke (::1) 472.20ms
2023-06-07 22:21:33,964 - ERROR - Uncaught exception GET /country?name=America (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country?name=America', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 136, in get
    'capital': capital,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'capital' where it is not associated with a value
2023-06-07 22:21:33,965 - ERROR - 500 GET /country?name=America (::1) 140.51ms
2023-06-07 22:25:27,249 - INFO - 200 GET /joke (::1) 432.51ms
2023-06-07 22:25:36,419 - WARNING - 400 GET /country (::1): Missing argument name
2023-06-07 22:25:36,419 - WARNING - 400 GET /country (::1) 0.72ms
2023-06-07 22:25:54,978 - ERROR - Uncaught exception GET /country?name=Israel (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/country?name=Israel', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/natalie/Voom/voomWarmUp/voomApp.py", line 136, in get
    'capital': capital,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'capital' where it is not associated with a value
2023-06-07 22:25:54,980 - ERROR - 500 GET /country?name=Israel (::1) 133.58ms
2023-06-07 22:27:13,109 - INFO - 200 GET /weather (::1) 177.41ms
2023-06-07 22:27:13,293 - INFO - 200 GET /weather (::1) 179.63ms
2023-06-07 22:27:13,420 - INFO - 200 GET /joke (::1) 493.28ms
2023-06-07 22:27:13,876 - INFO - 200 GET /joke (::1) 452.84ms
2023-06-07 22:27:16,084 - INFO - 200 GET /country?name=America (::1) 144.69ms
